networks:
  app-net:
    name: ${APP_NET:-upme_net}
    driver: bridge

services:
  auth-service:
    build: ../backend/services/auth-service
    ports:
      - "8081:8080"
    networks: [app-net]

  api-gateway:
    build: ../backend/gateway/api-gateway
    environment:
      GATEWAY_PORT: 8080
      AUTH_URL: http://auth-service:8080
      CORS_ORIGINS: ${CORS_ORIGINS}
    depends_on: [auth-service]
    ports:
      - "8080:8080"
    networks: [app-net]

  frontend:
    build: ../frontend/app
    depends_on: [api-gateway]
    ports:
      - "5173:80"
    networks: [app-net]