name: upme

networks:
  app-net:
    name: ${APP_NET:-upme_net}
    driver: bridge

volumes:
  auth-db-data:
  profile-db-data:
  minio-data:

services:
  api-gateway:
    build: ../backend/gateway/api-gateway
    environment:
      GATEWAY_PORT: 8080
      AUTH_URL: http://auth-service:8081
      PROFILE_URL: http://profile-service:8082
      CORS_ORIGINS: ${CORS_ORIGINS}
    depends_on: [ auth-service ]
    ports:
      - "8080:8080"
    networks: [ app-net ]


  auth-service:
    build: ../backend/services/auth-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/${DB_NAME_AUTH}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TTL_MIN: 600
      JWT_REFRESH_TTL_DAYS: 7
    networks: [app-net]
    depends_on:
      - auth-db

  auth-db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: ${DB_NAME_AUTH}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks: [ app-net ]
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  profile-service:
    build: ../backend/services/profile-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://profile-db:5432/${DB_NAME_PROFILE}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TTL_MIN: 600
      JWT_REFRESH_TTL_DAYS: 7
      S3_ACCESS_KEY: ${MINIO_ROOT_USER}
      S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      S3_BUCKET: ${S3_BUCKET_PROFILE}
    networks: [ app-net ]
    depends_on:
      - profile-db

  profile-db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: ${DB_NAME_PROFILE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks: [ app-net ]
    volumes:
      - profile-db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console
    volumes:
      - minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ app-net ]

  minio-init-profile:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10 &&
      mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc mb -p myminio/${S3_BUCKET_PROFILE} &&
      mc anonymous set public myminio/${S3_BUCKET_PROFILE} &&
      exit 0
      "
    networks:
      - app-net

  frontend:
    build: ../frontend
    depends_on: [api-gateway]
    ports:
      - "5173:80"
    networks: [app-net]



