name: upme

networks:
  app-net:
    name: ${APP_NET:-upme_net}
    driver: bridge

volumes:
  db-data: {}

services:
  api-gateway:
    build: ../backend/gateway/api-gateway
    environment:
      GATEWAY_PORT: 8080
      AUTH_URL: http://auth-service:8080
      CORS_ORIGINS: ${CORS_ORIGINS}
    depends_on: [ auth-service ]
    ports:
      - "8080:8080"
    networks: [ app-net ]


  auth-service:
    build: ../backend/services/auth-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TTL_MIN: 600
      JWT_REFRESH_TTL_DAYS: 7
    networks: [app-net]
    depends_on:
      - auth-db

  auth-db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks: [ app-net ]
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    build: ../frontend
    depends_on: [api-gateway]
    ports:
      - "5173:80"
    networks: [app-net]



